CREATE TABLE tw_group (
	id serial PRIMARY KEY,
	group_name varchar(20) UNIQUE NOT NULL,
	create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
	update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(0)
)